// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: file_changes.sql

package db

import (
	"context"
	"database/sql"
)

const createFileChange = `-- name: CreateFileChange :one
INSERT INTO file_changes (id, session_id, file_path, operation, old_content, new_content, diff, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, session_id, file_path, operation, old_content, new_content, diff, created_at
`

type CreateFileChangeParams struct {
	ID         string         `json:"id"`
	SessionID  string         `json:"session_id"`
	FilePath   string         `json:"file_path"`
	Operation  string         `json:"operation"`
	OldContent sql.NullString `json:"old_content"`
	NewContent sql.NullString `json:"new_content"`
	Diff       sql.NullString `json:"diff"`
	CreatedAt  int64          `json:"created_at"`
}

func (q *Queries) CreateFileChange(ctx context.Context, arg CreateFileChangeParams) (FileChange, error) {
	row := q.db.QueryRowContext(ctx, createFileChange,
		arg.ID,
		arg.SessionID,
		arg.FilePath,
		arg.Operation,
		arg.OldContent,
		arg.NewContent,
		arg.Diff,
		arg.CreatedAt,
	)
	var i FileChange
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.FilePath,
		&i.Operation,
		&i.OldContent,
		&i.NewContent,
		&i.Diff,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFileChange = `-- name: DeleteFileChange :exec
DELETE FROM file_changes WHERE id = ?
`

func (q *Queries) DeleteFileChange(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFileChange, id)
	return err
}

const deleteFileChangesBySession = `-- name: DeleteFileChangesBySession :exec
DELETE FROM file_changes WHERE session_id = ?
`

func (q *Queries) DeleteFileChangesBySession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteFileChangesBySession, sessionID)
	return err
}

const getFileChange = `-- name: GetFileChange :one
SELECT id, session_id, file_path, operation, old_content, new_content, diff, created_at FROM file_changes WHERE id = ?
`

func (q *Queries) GetFileChange(ctx context.Context, id string) (FileChange, error) {
	row := q.db.QueryRowContext(ctx, getFileChange, id)
	var i FileChange
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.FilePath,
		&i.Operation,
		&i.OldContent,
		&i.NewContent,
		&i.Diff,
		&i.CreatedAt,
	)
	return i, err
}

const listFileChangesBySession = `-- name: ListFileChangesBySession :many
SELECT id, session_id, file_path, operation, old_content, new_content, diff, created_at FROM file_changes WHERE session_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListFileChangesBySession(ctx context.Context, sessionID string) ([]FileChange, error) {
	rows, err := q.db.QueryContext(ctx, listFileChangesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FileChange{}
	for rows.Next() {
		var i FileChange
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.FilePath,
			&i.Operation,
			&i.OldContent,
			&i.NewContent,
			&i.Diff,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
