// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type FileChange struct {
	ID         string         `json:"id"`
	SessionID  string         `json:"session_id"`
	FilePath   string         `json:"file_path"`
	Operation  string         `json:"operation"`
	OldContent sql.NullString `json:"old_content"`
	NewContent sql.NullString `json:"new_content"`
	Diff       sql.NullString `json:"diff"`
	CreatedAt  int64          `json:"created_at"`
}

type Message struct {
	ID        string         `json:"id"`
	SessionID string         `json:"session_id"`
	Role      string         `json:"role"`
	Content   string         `json:"content"`
	Model     sql.NullString `json:"model"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

type Session struct {
	ID               string        `json:"id"`
	Title            string        `json:"title"`
	Model            string        `json:"model"`
	Provider         string        `json:"provider"`
	MessageCount     sql.NullInt64 `json:"message_count"`
	PromptTokens     sql.NullInt64 `json:"prompt_tokens"`
	CompletionTokens sql.NullInt64 `json:"completion_tokens"`
	CreatedAt        int64         `json:"created_at"`
	UpdatedAt        int64         `json:"updated_at"`
}
