// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CountMessagesBySession(ctx context.Context, sessionID string) (int64, error)
	CountSessions(ctx context.Context) (int64, error)
	CreateFileChange(ctx context.Context, arg CreateFileChangeParams) (FileChange, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteFileChange(ctx context.Context, id string) error
	DeleteFileChangesBySession(ctx context.Context, sessionID string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteMessagesBySession(ctx context.Context, sessionID string) error
	DeleteSession(ctx context.Context, id string) error
	GetFileChange(ctx context.Context, id string) (FileChange, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetSession(ctx context.Context, id string) (Session, error)
	ListFileChangesBySession(ctx context.Context, sessionID string) ([]FileChange, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
}

var _ Querier = (*Queries)(nil)
